name: Yehan Repo Sync Action
author: Ye Han <zhangtong.mr@aliyun.com>
description: Sync current repo to specified repo
branding:
  icon: upload-cloud
  color: blue
inputs:
  source_repo_url:
    description: source repo url
    required: true
  destination_repo_url:
    description: destination repo url
    required: true
  ssh_private_key:
    description: SSH_KEY
    required: true
runs:
  using: docker
  image: src/Dockerfile
  env:
    SSH_PRIVATE_KEY: ${{ inputs.ssh_private_key }}
  args:
    - ${{ inputs.source_repo_url }}
    - ${{ inputs.destination_repo_url }}